spring:
  application:
    name: democrud # Nome da aplicação, usado para identificação em logs e monitoramento.
  sql:
    init:
      mode: always # Garante que o banco de dados seja inicializado automaticamente ao iniciar a aplicação.
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/bancoDeDados;DB_CLOSE_DELAY=-1 # URL de conexão com o banco H2. 
    # DB_CLOSE_DELAY=-1 mantém o banco ativo mesmo após a desconexão.
    # url: jdbc:h2:mem:testdb # (Comentado) Exemplo de configuração para banco em memória.
    driverClassName: org.h2.Driver # Classe do driver JDBC para o banco H2.
    username: sa # Nome de usuário padrão para o banco H2.
    password: # Senha para o banco H2 (vazia por padrão).
  h2:
    console:
      enabled: true # Habilita o console web do H2 para visualização e manipulação do banco.
      path: /h2-console # Define o caminho de acesso ao console do H2.
  jpa:
    hibernate:
      ddl-auto: update # Configuração para o Hibernate atualizar automaticamente o esquema do banco.
    show-sql: true # Exibe as consultas SQL geradas pelo Hibernate no console.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # Dialeto do Hibernate para o banco H2.